#!/usr/bin/env python3
"""Brief 002 Part 2 — test the two pricing-surface assumptions directly against vendor implied vols.

1. Tenor: engine ATM vol (VIX/VIX3M variance-time interpolation to the leg's DTE) vs the vendor's
   ATM implied vol on the matched expiry chain (mean of call and put IV at the strike nearest spot).
2. Skew: vendor IV at each traded strike minus vendor ATM IV, per 1 % OTM, vs the engine's fixed
   +0.8 (puts) / -0.3 (calls) vol points per 1 % OTM.
Uses data/cache/optionsdx_extract.pkl (built by quote_join.py) and data/quotes/derived/legs_joined.csv.
Writes data/quotes/derived/surface_tables.md.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from spx_condor.pricing import atm_vol_for_tenor  # noqa: E402

DERIVED = ROOT / "data/quotes/derived"
OUT: list[str] = []


def p(s: str = "") -> None:
    OUT.append(s)


def md(df: pd.DataFrame, fmt: str = "{:.2f}") -> None:
    cols = list(df.columns)
    p("| " + " | ".join(str(c) for c in [df.index.name or ""] + cols) + " |")
    p("|" + "---|" * (len(cols) + 1))
    for idx, row in df.iterrows():
        p("| " + " | ".join([str(idx)] + [fmt.format(v) if isinstance(v, (float, np.floating)) else str(v) for v in row.values]) + " |")
    p()


def main() -> None:
    ex = pd.read_pickle(ROOT / "data/cache/optionsdx_extract.pkl")
    j = pd.read_csv(DERIVED / "legs_joined.csv", parse_dates=["date", "expiry", "label"])
    k = j[j.found & (j.bid > 0)].copy()                     # zero-bid legs have no meaningful IV
    # vendor ATM IV per (date, label)
    atm_rows = []
    for (d, lab), grp in k.groupby(["date", "label"]):
        ch = ex[(ex.QUOTE_DATE == d) & (ex.EXPIRE_DATE == lab)]
        spot = grp.spot.iloc[0]
        ch = ch.iloc[(ch.STRIKE - spot).abs().argsort()[:2]]     # two nearest strikes
        iv = pd.concat([ch.C_IV, ch.P_IV]).replace(0, np.nan).dropna()
        atm_rows.append(dict(date=d, label=lab, vendor_atm_iv=100 * iv.mean() if len(iv) else np.nan))
    atm = pd.DataFrame(atm_rows)
    k = k.merge(atm, on=["date", "label"], how="left")
    k["engine_atm"] = [100 * atm_vol_for_tenor(v, v3, d)[0] for v, v3, d in zip(k.vix, k.vix3m, k.dte)]
    k["vendor_iv"] = 100 * k.iv
    k["mny"] = 100 * (k.obs_strike / k.spot - 1)
    k["side"] = np.where(k.right == "P", "put", "call")
    k["when_"] = np.where(k.when == "entry", "entry (~45 DTE)", "exit (~21 DTE)")
    k["engine_leg_vol"] = np.where(k.right == "P", k.engine_atm + 0.8 * (-k.mny), k.engine_atm - 0.3 * k.mny)
    k["vendor_slope"] = (k.vendor_iv - k.vendor_atm_iv) / k.mny.abs()          # vol pts per 1 % OTM
    k["engine_slope"] = np.where(k.right == "P", 0.8, -0.3)
    p("# Surface tables (generated by scripts/quote_surface.py)")
    p()
    p(f"Legs with a positive bid and a vendor IV: {int(k.vendor_iv.notna().sum())} of {len(j)}. Vendor IV is the vendor's own "
      "inversion of the mid (model, r and q unknown); it is used for the slope and level comparison, not for pricing.")
    p()
    p("## 1. ATM vol level: engine tenor interpolation vs vendor ATM IV (vol points)")
    p()
    one = k.drop_duplicates(["date", "label"])
    one = one.assign(d=one.engine_atm - one.vendor_atm_iv)
    g = one.groupby("when_")
    md(pd.DataFrame({"chains": g.size(), "VIX median": g.vix.median(), "engine ATM median": g.engine_atm.median(),
                     "vendor ATM IV median": g.vendor_atm_iv.median(), "engine − vendor, median": g.d.median(),
                     "engine − vendor, IQR": g.d.quantile(0.75) - g.d.quantile(0.25)}).rename_axis("date type"))
    one["vix_regime"] = pd.cut(one.vix, [0, 15, 25, np.inf], labels=["VIX < 15", "VIX 15-25", "VIX > 25"])
    g = one.groupby(["when_", "vix_regime"], observed=True)
    md(pd.DataFrame({"chains": g.size(), "engine − vendor, median": g.d.median()}))
    p("## 2. Skew: vendor IV at the traded strike minus vendor ATM IV, per 1 % OTM (vol points)")
    p()
    p("Engine: +0.8 on the put side, −0.3 on the call side, constant across moneyness and tenor.")
    p()
    g = k.groupby(["side", "when_"])
    md(pd.DataFrame({"legs": g.size(), "|moneyness| median (%)": k.mny.abs().groupby([k.side, k.when_]).median(), "vendor slope median": g.vendor_slope.median(),
                     "vendor slope IQR": g.vendor_slope.quantile(0.75) - g.vendor_slope.quantile(0.25),
                     "engine slope": g.engine_slope.first(),
                     "vendor leg IV median": g.vendor_iv.median(), "engine leg vol median": g.engine_leg_vol.median(),
                     "engine − vendor leg vol, median": (k.engine_leg_vol - k.vendor_iv).groupby([k.side, k.when_]).median()}))
    k["vix_regime"] = pd.cut(k.vix, [0, 15, 25, np.inf], labels=["VIX < 15", "VIX 15-25", "VIX > 25"])
    g = k.groupby(["side", "vix_regime"], observed=True)
    md(pd.DataFrame({"legs": g.size(), "vendor slope median": g.vendor_slope.median(),
                     "engine − vendor leg vol, median": (k.engine_leg_vol - k.vendor_iv).groupby([k.side, k.vix_regime], observed=True).median()}))
    lo = (np.floor(k.mny.abs() / 2) * 2).clip(upper=20).astype(int)
    k["band"] = np.where(lo >= 20, "20 %+", lo.astype(str).str.zfill(2) + "-" + (lo + 2).astype(str) + " %")
    g = k.groupby(["side", "band"])
    md(pd.DataFrame({"legs": g.size(), "vendor slope median": g.vendor_slope.median(),
                     "vendor leg IV median": g.vendor_iv.median(), "engine leg vol median": g.engine_leg_vol.median()}))
    g = k.groupby(["side", k.date.dt.year])
    md(pd.DataFrame({"legs": g.size(), "vendor slope median": g.vendor_slope.median()}).rename_axis(["side", "year"]))
    k.to_csv(DERIVED / "legs_surface.csv", index=False, float_format="%.4f")
    text = "\n".join(OUT) + "\n"
    (DERIVED / "surface_tables.md").write_text(text)
    print(text)


if __name__ == "__main__":
    main()
