#!/usr/bin/env python3
"""Brief 002 Part 2 report tables from data/quotes/derived/legs_joined.csv.

(a) synthetic Black-Scholes mid vs observed mid, per leg and per cycle net credit;
(b) observed half-spread per leg and implied round-trip cost per cycle, incl. stress windows.
Buckets: moneyness (2 % bands of |K/S-1|), VIX regime (<15, 15-25, >25), DTE (entry ~45 / exit ~21),
side (put / call). Writes data/quotes/derived/report_tables.md and prints it.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
DERIVED = ROOT / "data/quotes/derived"
TRADES = ROOT / "results/2026-09-09_stage1/variant_a/trades.csv"
MULT, CONTRACTS, COMM = 100, 2, 1.25          # variant A: 2 contracts, $1.25/leg/contract (config.yaml)
ASSUMED_HS = 0.10                              # stage-1 flat half-spread per leg (points)
WINDOWS = {"Feb 2018": ("2018-02-01", "2018-02-28"), "Mar 2020": ("2020-03-01", "2020-03-31"),
           "2022": ("2022-01-01", "2022-12-31")}
SIGN = {"long_put": -1, "short_put": 1, "short_call": 1, "long_call": -1}
OUT: list[str] = []


def p(s: str = "") -> None:
    OUT.append(s)


def md(df: pd.DataFrame, floatfmt: str = "{:.3f}") -> None:
    cols = list(df.columns)
    p("| " + " | ".join(str(c) for c in [df.index.name or ""] + cols) + " |")
    p("|" + "---|" * (len(cols) + 1))
    for idx, row in df.iterrows():
        cells = [floatfmt.format(v) if isinstance(v, (float, np.floating)) and np.isfinite(v)
                 else ("" if isinstance(v, float) else str(v)) for v in row.values]
        p("| " + " | ".join([str(idx)] + cells) + " |")
    p()


def load() -> pd.DataFrame:
    j = pd.read_csv(DERIVED / "legs_joined.csv", parse_dates=["date", "expiry", "entry_date", "exit_date", "label"])
    k = j[j.found].copy()
    k["side"] = np.where(k.right == "P", "put", "call")
    k["position"] = np.where(k.leg.str.startswith("short"), "short", "long")
    k["dte_bucket"] = np.where(k.when == "entry", "entry (~45 DTE)", "exit (~21 DTE)")
    k["vix_regime"] = pd.cut(k.vix, [0, 15, 25, np.inf], labels=["VIX < 15", "VIX 15-25", "VIX > 25"])
    dist = (k.obs_strike / k.spot - 1).abs() * 100
    lo = (np.floor(dist / 2) * 2).clip(upper=20).astype(int)
    k["moneyness"] = np.where(lo >= 20, "20 %+", lo.astype(str).str.zfill(2) + "-" + (lo + 2).astype(str).str.zfill(2) + " %")
    k["synth"] = k.synth_mid_obs_strike
    k["diff"] = k.synth - k.obs_mid
    k["diff_pct"] = np.where(k.obs_mid > 0, 100 * k["diff"] / k.obs_mid, np.nan)
    k["year"] = k.date.dt.year
    return j, k


def diff_table(k: pd.DataFrame, by: str) -> pd.DataFrame:
    g = k.groupby(by, observed=True)
    t = pd.DataFrame({
        "legs": g.size(),
        "obs mid, median (pts)": g.obs_mid.median(),
        "synth − obs, mean (pts)": g["diff"].mean(),
        "synth − obs, median (pts)": g["diff"].median(),
        "IQR (pts)": g["diff"].quantile(0.75) - g["diff"].quantile(0.25),
        "synth − obs, median (% of obs)": g.diff_pct.median(),
        "IQR (% of obs)": g.diff_pct.quantile(0.75) - g.diff_pct.quantile(0.25),
    })
    t.index.name = by
    return t


def spread_table(k: pd.DataFrame, by: str) -> pd.DataFrame:
    g = k.groupby(by, observed=True)
    t = pd.DataFrame({"legs": g.size(), "median": g.half_spread.median(), "p75": g.half_spread.quantile(0.75),
                      "p90": g.half_spread.quantile(0.90), "mean": g.half_spread.mean(),
                      "zero-bid legs": g.zero_bid.sum().astype(int)})
    t.index.name = by
    return t


def cycle_nets(j: pd.DataFrame) -> pd.DataFrame:
    """Per cycle and date: synthetic and observed net (credit at entry, debit at exit), only where all 4 legs joined."""
    d = j.copy()
    d["sgn"] = d.leg.map(SIGN)
    d["obs_signed"] = d.sgn * d.obs_mid
    d["synth_signed"] = d.sgn * d.synth_mid_obs_strike
    g = d.groupby(["cycle", "when"])
    n = pd.DataFrame({"complete": g.found.all(), "obs_net": g.obs_signed.sum(), "synth_net": g.synth_signed.sum(),
                      "hs_sum": g.half_spread.sum(), "vix": g.vix.first(), "date": g.date.first(),
                      "substituted": g.substituted.any()})
    return n[n.complete].drop(columns="complete")


def main() -> None:
    j, k = load()
    t = pd.read_csv(TRADES, parse_dates=["entry_date", "exit_date"])
    t = t[(t.entry_date >= "2010-01-01") & (t.exit_date <= "2023-12-31")].reset_index(drop=True)
    n_legs, n_found = len(j), int(j.found.sum())
    p("# Part 2 report tables (generated by scripts/quote_report.py)")
    p()
    p(f"Legs joined {n_found} of {n_legs} ({100 * n_found / n_legs:.1f} %); substituted strikes {int(k.substituted.sum())}; "
      f"zero-bid legs {int(k.zero_bid.sum())} (observed mid = ask/2, kept). Points are index points; dollars are per "
      f"variant-A cycle (2 contracts, $100 multiplier) unless stated.")
    p()
    # ---------------------------------------------------------------- (a)
    p("## (a) Synthetic mid − observed mid, per leg")
    p()
    for by, title in [("moneyness", "By moneyness (|K/S − 1|, 2 % bands)"), ("vix_regime", "By VIX regime on the quote date"),
                      ("dte_bucket", "By DTE"), ("side", "By side"), ("leg", "By leg"), ("substituted", "Exact vs substituted strike"),
                      ("year", "By year")]:
        p(f"### {title}")
        p()
        md(diff_table(k, by))
    p("### Net credit / debit per cycle, synthetic vs observed (cycles with all four legs on that date)")
    p()
    n = cycle_nets(j)
    rows = []
    for when, lab in (("entry", "entry credit"), ("exit", "exit debit")):
        x = n.xs(when, level="when")
        d = x.synth_net - x.obs_net
        rows.append({"quantity": lab, "cycles": len(x), "observed, median (pts)": x.obs_net.median(),
                     "synthetic, median (pts)": x.synth_net.median(), "synth − obs, mean (pts)": d.mean(),
                     "synth − obs, median (pts)": d.median(), "IQR (pts)": d.quantile(0.75) - d.quantile(0.25),
                     "synth − obs, median (% of obs)": (100 * d / x.obs_net).median(),
                     "synth − obs, mean ($ / cycle)": d.mean() * MULT * CONTRACTS})
    md(pd.DataFrame(rows).set_index("quantity"))
    p("### Net entry credit by VIX regime")
    p()
    x = n.xs("entry", level="when").copy()
    x["vix_regime"] = pd.cut(x.vix, [0, 15, 25, np.inf], labels=["VIX < 15", "VIX 15-25", "VIX > 25"])
    x["d"] = x.synth_net - x.obs_net
    g = x.groupby("vix_regime", observed=True)
    tt = pd.DataFrame({"cycles": g.size(), "observed credit, median (pts)": g.obs_net.median(),
                       "synthetic credit, median (pts)": g.synth_net.median(), "synth − obs, median (pts)": g.d.median(),
                       "synth − obs, median (% of obs)": g.apply(lambda z: (100 * z.d / z.obs_net).median())})
    tt.index.name = "vix_regime"
    md(tt)
    # premium P&L repricing on fully joined cycles, exit dates held fixed
    ent = n.xs("entry", level="when"); ext = n.xs("exit", level="when")
    both = ent.join(ext, lsuffix="_in", rsuffix="_out", how="inner")
    tr = t.loc[both.index]
    comm = 8 * COMM * CONTRACTS
    pnl = {
        "stage 1 as run (synthetic mids, flat 0.10/leg, $1.25/leg)": tr.pnl_usd.sum(),
        "synthetic mids, flat 0.10/leg": ((both.synth_net_in - 4 * ASSUMED_HS) - (both.synth_net_out + 4 * ASSUMED_HS)).sum() * MULT * CONTRACTS - comm * len(both),
        "observed mids, flat 0.10/leg": ((both.obs_net_in - 4 * ASSUMED_HS) - (both.obs_net_out + 4 * ASSUMED_HS)).sum() * MULT * CONTRACTS - comm * len(both),
        "synthetic mids, observed spreads": ((both.synth_net_in - both.hs_sum_in) - (both.synth_net_out + both.hs_sum_out)).sum() * MULT * CONTRACTS - comm * len(both),
        "observed mids, observed spreads": ((both.obs_net_in - both.hs_sum_in) - (both.obs_net_out + both.hs_sum_out)).sum() * MULT * CONTRACTS - comm * len(both),
    }
    p(f"### Premium P&L repriced on the {len(both)} cycles with all eight legs (variant A, exit dates as in stage 1)")
    p()
    p("Repricing only — entry/exit decisions are the stage-1 ones. Bid-ask is charged as the sum of the four "
      "half-spreads on each side (fill at bid on sells, ask on buys); commissions $1.25/leg/contract as in stage 1.")
    p()
    md(pd.DataFrame({"premium P&L ($)": pnl}).rename_axis("pricing"), "{:,.0f}")
    both.to_csv(DERIVED / "cycle_nets.csv", float_format="%.4f")
    # ---------------------------------------------------------------- (b)
    p("## (b) Observed half-spread per leg (index points)")
    p()
    for by, title in [("moneyness", "By moneyness"), ("vix_regime", "By VIX regime"), ("dte_bucket", "By DTE"),
                      ("side", "By side"), ("position", "Short vs long legs"), ("substituted", "Exact vs substituted strike"),
                      ("year", "By year")]:
        p(f"### {title}")
        p()
        md(spread_table(k, by))
    p("### Half-spread median by moneyness band × VIX regime (Part 4 lookup candidate; legs in brackets)")
    p()
    pv = k.pivot_table(index="moneyness", columns="vix_regime", values="half_spread", aggfunc="median", observed=True)
    ct = k.pivot_table(index="moneyness", columns="vix_regime", values="half_spread", aggfunc="size", observed=True)
    cell = pv.copy().astype(object)
    for r_ in pv.index:
        for c_ in pv.columns:
            cell.loc[r_, c_] = f"{pv.loc[r_, c_]:.3f} [{int(ct.loc[r_, c_])}]" if np.isfinite(pv.loc[r_, c_]) else ""
    md(cell)
    p("### Half-spread median by era × VIX regime × DTE")
    p()
    k["era"] = np.where(k.year <= 2016, "2010-2016", "2017-2023")
    pv = k.pivot_table(index=["era", "dte_bucket"], columns="vix_regime", values="half_spread", aggfunc="median", observed=True)
    md(pv)
    p("### Half-spread median by era × side × DTE")
    p()
    md(k.pivot_table(index=["era", "side"], columns="dte_bucket", values="half_spread", aggfunc="median", observed=True))
    p("### All legs")
    p()
    allq = k.half_spread.quantile([0.5, 0.75, 0.9])
    md(pd.DataFrame({"legs": [len(k)], "median": [allq[0.5]], "p75": [allq[0.75]], "p90": [allq[0.9]], "mean": [k.half_spread.mean()]},
                    index=pd.Index(["all"], name="")))
    # round trip per cycle
    rt = both.hs_sum_in + both.hs_sum_out
    p(f"### Implied round-trip bid-ask cost per cycle ({len(both)} fully joined cycles)")
    p()
    p("Sum of eight half-spreads (four legs in, four legs out). Stage 1 assumed 0.10 per leg = 0.80 pts = $80 per contract.")
    p()
    r = pd.DataFrame({"pts per contract": rt.quantile([0.5, 0.75, 0.9]).tolist() + [rt.mean()],
                      "$ per contract": (rt.quantile([0.5, 0.75, 0.9]).tolist() + [rt.mean()])},
                     index=pd.Index(["median", "p75", "p90", "mean"], name=""))
    r["$ per contract"] *= MULT
    r["$ per cycle, 2 contracts"] = r["$ per contract"] * CONTRACTS
    r["equivalent flat per leg (pts)"] = r["pts per contract"] / 8
    md(r, "{:,.2f}")
    p("### Round trip by year")
    p()
    yr = rt.groupby(both.date_in.dt.year)
    md(pd.DataFrame({"cycles": yr.size(), "median (pts)": yr.median(), "p75 (pts)": yr.quantile(0.75),
                     "median ($, 2 contracts)": yr.median() * MULT * CONTRACTS}).rename_axis("year"), "{:,.2f}")
    p("### Stress windows")
    p()
    p("Legs quoted on dates inside the window (entry or exit), and round trips of fully joined cycles whose entry "
      "or exit date lies inside it.")
    p()
    rows = []
    for w, (a, b) in WINDOWS.items():
        kk = k[(k.date >= a) & (k.date <= b)]
        bb = both[((both.date_in >= a) & (both.date_in <= b)) | ((both.date_out >= a) & (both.date_out <= b))]
        rtw = bb.hs_sum_in + bb.hs_sum_out
        rows.append({"window": w, "legs": len(kk), "half-spread median": kk.half_spread.median(), "p75": kk.half_spread.quantile(0.75),
                     "p90": kk.half_spread.quantile(0.9), "cycles": len(bb), "round trip median (pts)": rtw.median(),
                     "round trip median ($, 2 contracts)": rtw.median() * MULT * CONTRACTS})
    kk = k[~((k.date.dt.year == 2022) | k.date.between("2018-02-01", "2018-02-28") | k.date.between("2020-03-01", "2020-03-31"))]
    rows.append({"window": "all other dates", "legs": len(kk), "half-spread median": kk.half_spread.median(),
                 "p75": kk.half_spread.quantile(0.75), "p90": kk.half_spread.quantile(0.9), "cycles": np.nan,
                 "round trip median (pts)": np.nan, "round trip median ($, 2 contracts)": np.nan})
    md(pd.DataFrame(rows).set_index("window"), "{:,.3f}")
    # headline placement
    p("## Headline placement against the brief's table")
    p()
    hs_med = k.half_spread.median(); rt_med = rt.median() / 8
    tbl = {0.10: (48264, 71742), 0.15: (25704, 1822), 0.20: (3144, -68098)}
    def interp(hs):
        a = 48264 - (hs - 0.10) / 0.05 * (48264 - 25704); b = 71742 - (hs - 0.10) / 0.05 * (71742 - 1822)
        return a, b
    rows = [{"assumed half-spread per leg (pts)": f"{h:.2f} (brief)", "variant A premium P&L ($)": tbl[h][0], "variant B ($)": tbl[h][1]} for h in tbl]
    for lab, h in (("observed median per leg", hs_med), ("observed round trip / 8", rt_med)):
        a, b = interp(h)
        rows.append({"assumed half-spread per leg (pts)": f"{h:.3f} ({lab})", "variant A premium P&L ($)": a, "variant B ($)": b})
    md(pd.DataFrame(rows).set_index("assumed half-spread per leg (pts)"), "{:,.0f}")
    p("Linear in the half-spread (each 0.05 pts/leg = $40 per contract per cycle × 282 cycles × contracts), as in the brief. "
      "Mid error from (a) is not included.")
    text = "\n".join(OUT) + "\n"
    (DERIVED / "report_tables.md").write_text(text)
    print(text)


if __name__ == "__main__":
    main()
